name: Generar EPG DSports Oficial

on:
  schedule:
    - cron: '0 6 * * *' # Todos los días a las 03:00 AM hora Argentina
  workflow_dispatch: # Permite ejecución manual

jobs:
  run-webgrab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Ejecutar WebGrab+Plus
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/config \
          -v ${{ github.workspace }}:/data \
          m3u2htsp/webgrabplus

    - name: Commit y Push del XML generado
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add epg-dsports.xml
        git commit -m "Auto-update DSports EPG" || exit 0
        git push
